### ISSUE TITLE
Token lost on refreshing/rebooting browser

### ISSUE THREAD

**Issue by ankitgoyal2042** [zackargyle/angularjs-django-rest-framework-seed#2]
Hi Zack. Thanks for the great solution to authentication in Angular. But the authentication token gets lost when I refresh the application on doing any changes in the code. What would be your advice to handle this?

**Comment by zackargyle** [comment]
Hey,

I'm glad you emailed me this, I knew this was a question people have been
having, so I've been working on adding it to the seed. Thanks for the
reminder, I just committed the changes, now it persists the token. Hope it
is helpful, I would love to answer any questions about it.

Zack

On Fri, Dec 20, 2013 at 5:55 AM, ankitgoyal2042 notifications@github.comwrote:

> Hi Zack. Thanks for the great solution to authentication in Angular. But
> the authentication token gets lost when I refresh the application on doing
> any changes in the code. What would be your advice to handle this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zackargyle/angularjs-django-rest-framework-seed/issues/2
> .

## 

_Zack Argyle_
_Software Engineer_

**Comment by ankitgoyal2042** [comment]
Works perfectly! This has been immensely helpful. Thanks a lot.
